<?php

use Illuminate\Database\Seeder;
use App\Models\Project\ProjectSurvey;

class ProjectSurveyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $project_1 = [
            [
                'code' => '0001',
                'project_vendor_id' => 1,
                'project_id' => 1,
                'project_code' => '18120482US',
                'vendor_id' => 1,
                'vendor_code' => '1111',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
            [
                'code' => '0002',
                'project_vendor_id' => 2,
                'project_id' => 1,
                'project_code' => '18120482US',
                'vendor_id' => 2,
                'vendor_code' => '1185',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
            [
                'code' => '0003',
                'project_vendor_id' => 3,
                'project_id' => 1,
                'project_code' => '18120482US',
                'vendor_id' => 3,
                'vendor_code' => '2287',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
            [
                'code' => '0004',
                'project_vendor_id' => 4,
                'project_id' => 1,
                'project_code' => '18120482US',
                'vendor_id' => 4,
                'vendor_code' => '3388',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
            [
                'code' => '0005',
                'project_vendor_id' => 5,
                'project_id' => 1,
                'project_code' => '18120482US',
                'vendor_id' => 6,
                'vendor_code' => 'SJPL',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
        ];

        foreach ($project_1 as $survey) {
            ProjectSurvey::create($survey);
        }

        $project_2 = [
            [
                'code' => '0006',
                'project_vendor_id' => 6,
                'project_id' => 2,
                'project_code' => '18120484UK',
                'vendor_id' => 1,
                'vendor_code' => '1111',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
            [
                'code' => '0007',
                'project_vendor_id' => 7,
                'project_id' => 2,
                'project_code' => '18120484UK',
                'vendor_id' => 2,
                'vendor_code' => '1185',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
            [
                'code' => '0008',
                'project_vendor_id' => 8,
                'project_id' => 2,
                'project_code' => '18120484UK',
                'vendor_id' => 3,
                'vendor_code' => '2287',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],
            [
                'code' => '0009',
                'project_vendor_id' => 9,
                'project_id' => 2,
                'project_code' => '18120484UK',
                'vendor_id' => 2,
                'vendor_code' => '3388',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],

            [
                'code' => '0010',
                'project_vendor_id' => 2,
                'project_id' => 1,
                'project_code' => '18120482US',
                'vendor_id' => 2,
                'vendor_code' => '1185',
                //'survey_live_url',
                //'survey_test_url',
                'sy_excl_link_flag' => false,
                //'syv_complete',
                //'syv_terminate',
                //'syv_quotafull',
                //'syv_qualityterm',
                //'syv_other_url',
                'collection_dedupe' => false,
                'status_id' => 1,
                'status_label' => 'Pending Launch',
            ],

        ];

        foreach ($project_2 as $survey) {
            ProjectSurvey::create($survey);
        }

    }
}
